In [2]:
# execution performance
size = 10_000_000

#python list 
py_list = list(range(size))
start = time.time()
sq_list = (x**2 for x in py_list)
end = time.time()
print(f"python list time = {end-start} seconds")


# numpy array
np_arry = np.array(py_list)
start = time.time()
sq_arry = np_arry ** 2
end = time.time()
print(f"Numpy array time = {end-start} seconds")

python list time = 0.00013756752014160156 seconds
Numpy array time = 0.03864240646362305 seconds


In [3]:
# Create numpy array 
arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr, type(arr), arr.shape)

arr2 = np.array([1,2,3,4,5,"sabbir"])
print(arr2, type(arr), arr.shape)

arr2d = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(arr2d, type(arr2d), arr2d.shape)

[1 2 3 4 5 6 7 8 9] <class 'numpy.ndarray'> (9,)
['1' '2' '3' '4' '5' 'sabbir'] <class 'numpy.ndarray'> (9,)
[[1 2 3]
 [4 5 6]
 [7 8 9]] <class 'numpy.ndarray'> (3, 3)


In [4]:
# Creating Array using Built in method 
arr1 =  np.zeros((2,4), dtype="int64") #prefill
print(arr1, arr1.shape)

arr2 = np.ones((5, )) #prefill
print(arr2, arr2.shape)

arr3 = np.full((3,4), 100) #prefill with value
print(arr3, arr3.shape)

arr4 = np.eye(3) #indentity matrix
print(arr4, arr4.shape)

arr5 = np.arange(8, 11, 2) #ranage elements
print(arr5, arr5.shape)

arr6 = np.linspace(1, 100, 10) # evenly spacede array
print(arr6, arr6.shape)

[[0 0 0 0]
 [0 0 0 0]] (2, 4)
[1. 1. 1. 1. 1.] (5,)
[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]] (3, 4)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] (3, 3)
[ 8 10] (2,)
[  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.] (10,)


In [5]:
# Operations on array

arr = np.array([[1,2,3], [4,5,6]])
print(arr, arr.shape)

reshaped = arr.reshape((3,2))
print(reshaped, reshaped.shape)


[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)


In [6]:
# Multi-dimensional array

arr2d = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(arr2d)

print(np.sum(arr2d))

sum_of_colums = np.sum(arr2d, axis = 0)
print(sum_of_colums)

sum_of_row = np.sum(arr2d, axis = 1)
print(sum_of_row)

print(arr2d[0:2, 1:3])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]
[ 6 15 24]
[[2 3]
 [5 6]]


In [7]:
# 3D Array 
arr3D = np.array([[[1,2,3], [4,5,6]], [[7,8,9,], [10,11,12]]])

print(arr3D, arr3D.shape)

# Indexing 
print(arr3D[1, 1, 0])

# slicing
arr3D[:, 0, :] = 99 

print(arr3D)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]] (2, 2, 3)
10
[[[99 99 99]
  [ 4  5  6]]

 [[99 99 99]
  [10 11 12]]]


In [8]:
# normalize 

arr = np.array([[1,2], [3,4]])
mean = np.mean(arr)
std_dev = np.std(arr)

normalized_arr = (arr-mean/std_dev)
print(normalized_arr)



[[-1.23606798 -0.23606798]
 [ 0.76393202  1.76393202]]


In [15]:
# Mathmetical fnx
# aggregation 

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

print(np.sum(arr))
print(np.prod(arr))
print(np.min(arr))
print(np.max(arr))
print(np.argmin(arr))
print(np.argmax(arr))

print(np.mean(arr))
print(np.std(arr))
print(np.median(arr))
print(np.var(arr))

45
362880
1
9
0
8
5.0
2.581988897471611
5.0
6.666666666666667
